/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author alyne.morais
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menFornecedor = new javax.swing.JMenu();
        menExplorarFornecedor = new javax.swing.JMenuItem();
        menProduto = new javax.swing.JMenu();
        menExplorarProduto = new javax.swing.JMenuItem();
        menCliente = new javax.swing.JMenu();
        menExplorarCliente = new javax.swing.JMenuItem();
        menEntrada = new javax.swing.JMenu();
        menExplorarEntrada = new javax.swing.JMenuItem();
        menSaida = new javax.swing.JMenu();
        menExplorarSaida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Estoque");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(670, 480));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/estoque.png"))); // NOI18N

        lblData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData.setText("Data");

        menFornecedor.setText("Fornecedor");
        menFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menFornecedorActionPerformed(evt);
            }
        });

        menExplorarFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        menExplorarFornecedor.setText("Cadastro Fornecedor");
        menExplorarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menExplorarFornecedorActionPerformed(evt);
            }
        });
        menFornecedor.add(menExplorarFornecedor);

        jMenuBar1.add(menFornecedor);

        menProduto.setText("Produto");
        menProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menProdutoActionPerformed(evt);
            }
        });

        menExplorarProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        menExplorarProduto.setText("Cadastrar Produto");
        menExplorarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menExplorarProdutoActionPerformed(evt);
            }
        });
        menProduto.add(menExplorarProduto);

        jMenuBar1.add(menProduto);

        menCliente.setText("Cliente");
        menCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menClienteActionPerformed(evt);
            }
        });

        menExplorarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menExplorarCliente.setText("Cadastro Cliente");
        menExplorarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menExplorarClienteActionPerformed(evt);
            }
        });
        menCliente.add(menExplorarCliente);

        jMenuBar1.add(menCliente);

        menEntrada.setText("Entrada");

        menExplorarEntrada.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menExplorarEntrada.setText(" Cadastro Entrada");
        menExplorarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menExplorarEntradaActionPerformed(evt);
            }
        });
        menEntrada.add(menExplorarEntrada);

        jMenuBar1.add(menEntrada);

        menSaida.setText("Saída");

        menExplorarSaida.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menExplorarSaida.setText("Cadastro Saída");
        menExplorarSaida.setToolTipText("");
        menExplorarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menExplorarSaidaActionPerformed(evt);
            }
        });
        menSaida.add(menExplorarSaida);

        jMenuBar1.add(menSaida);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblData)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        setSize(new java.awt.Dimension(1021, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menFornecedorActionPerformed

    }//GEN-LAST:event_menFornecedorActionPerformed

    private void menExplorarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menExplorarFornecedorActionPerformed
//as linhas abaixo vão abrir o form TelaUsuario dentro do desktop pane
        TelaFornecedor fornecedor = new TelaFornecedor();
        fornecedor.setVisible(true);
        desktop.add(fornecedor);

    }//GEN-LAST:event_menExplorarFornecedorActionPerformed

    private void menExplorarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menExplorarProdutoActionPerformed
        //as linhas abaixo vão abrir o form TelaProduto dentro do desktop pane
        TelaProduto produto = new TelaProduto();
        produto.setVisible(true);
        desktop.add(produto);
    }//GEN-LAST:event_menExplorarProdutoActionPerformed

    private void menProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menProdutoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // as linhas abaixo substituem a label data ldldata pela data atual do
        // sistema ao iniciar o form(
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.FULL);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menExplorarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menExplorarClienteActionPerformed
        //as linhas abaixo vão abrir o form TelaProduto dentro do desktop pane
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);
    }//GEN-LAST:event_menExplorarClienteActionPerformed

    private void menClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menClienteActionPerformed
        
    }//GEN-LAST:event_menClienteActionPerformed

    private void menExplorarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menExplorarEntradaActionPerformed
        //as linhas abaixo vão abrir o form TelaEntrada dentro do desktop pane
        TelaEntrada entrada = new TelaEntrada();
        entrada.setVisible(true);
        desktop.add(entrada);
    }//GEN-LAST:event_menExplorarEntradaActionPerformed

    private void menExplorarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menExplorarSaidaActionPerformed
        //as linhas abaixo vão abrir o form TelaSaida dentro do desktop pane
        TelaSaida entrada = new TelaSaida();
        entrada.setVisible(true);
        desktop.add(entrada);
    }//GEN-LAST:event_menExplorarSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblData;
    private javax.swing.JMenu menCliente;
    private javax.swing.JMenu menEntrada;
    private javax.swing.JMenuItem menExplorarCliente;
    private javax.swing.JMenuItem menExplorarEntrada;
    private javax.swing.JMenuItem menExplorarFornecedor;
    private javax.swing.JMenuItem menExplorarProduto;
    private javax.swing.JMenuItem menExplorarSaida;
    private javax.swing.JMenu menFornecedor;
    private javax.swing.JMenu menProduto;
    private javax.swing.JMenu menSaida;
    // End of variables declaration//GEN-END:variables
}
